cmake_minimum_required(VERSION 3.16)
project(ffuzzy_test C)
set(CMAKE_C_STANDARD 11)
add_executable(ffuzzy_test test_main.c ../src/scorer.c ../src/corpus.c ../src/thread_pool.c ../src/ffuzzy.c)
target_include_directories(ffuzzy_test PRIVATE ../src)
if(UNIX)
    target_link_libraries(ffuzzy_test pthread)
endif()
