// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/fuzzy.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1193813323;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_ffuzzy',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  void crateApiFuzzyFuzzyCorpusAdd(
      {required FuzzyCorpus that, required List<String> items});

  void crateApiFuzzyFuzzyCorpusClear({required FuzzyCorpus that});

  List<FuzzyHit> crateApiFuzzyFuzzyCorpusFilter(
      {required FuzzyCorpus that,
      required String query,
      required FuzzyConfig config,
      int? limit});

  Future<List<FuzzyHit>> crateApiFuzzyFuzzyCorpusFilterAsync(
      {required FuzzyCorpus that,
      required String query,
      required FuzzyConfig config,
      int? limit});

  void crateApiFuzzyFuzzyCorpusFree({required FuzzyCorpus that});

  bool crateApiFuzzyFuzzyCorpusIsEmpty({required FuzzyCorpus that});

  bool crateApiFuzzyFuzzyCorpusIsHydrated({required FuzzyCorpus that});

  int crateApiFuzzyFuzzyCorpusLen({required FuzzyCorpus that});

  FuzzyCorpus crateApiFuzzyFuzzyCorpusNew(
      {required List<String> items, required bool ignoreCaseIndices});

  void crateApiFuzzyFuzzyCorpusRehydrate({required FuzzyCorpus that});

  void crateApiFuzzyFuzzyCorpusRemoveIndices(
      {required FuzzyCorpus that, required List<int> indices});

  void crateApiFuzzyFuzzyCorpusSetAt(
      {required FuzzyCorpus that, required int index, required String item});

  FuzzyConfig crateApiFuzzyDefaultFuzzyConfig();

  Future<FuzzyConfig> crateApiFuzzyFuzzyConfigDefault();

  Future<FuzzyCorpus> crateApiFuzzyFuzzyCorpusNewAsync(
      {required List<String> items, required bool ignoreCaseIndices});

  List<FuzzyHit> crateApiFuzzyFuzzyFilter(
      {required String query,
      required List<String> items,
      required FuzzyConfig config,
      int? limit});

  Future<List<FuzzyHit>> crateApiFuzzyFuzzyFilterAsync(
      {required String query,
      required List<String> items,
      required FuzzyConfig config,
      int? limit});

  int? crateApiFuzzyFuzzyMatch(
      {required String query,
      required String haystack,
      required FuzzyConfig config});

  FuzzyMatch? crateApiFuzzyFuzzyMatchIndices(
      {required String query,
      required String haystack,
      required FuzzyConfig config});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_FuzzyCorpus;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_FuzzyCorpus;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_FuzzyCorpusPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiFuzzyFuzzyCorpusAdd(
      {required FuzzyCorpus that, required List<String> items}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        sse_encode_list_String(items, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusAddConstMeta,
      argValues: [that, items],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusAddConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_add",
        argNames: ["that", "items"],
      );

  @override
  void crateApiFuzzyFuzzyCorpusClear({required FuzzyCorpus that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusClearConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusClearConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_clear",
        argNames: ["that"],
      );

  @override
  List<FuzzyHit> crateApiFuzzyFuzzyCorpusFilter(
      {required FuzzyCorpus that,
      required String query,
      required FuzzyConfig config,
      int? limit}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        sse_encode_String(query, serializer);
        sse_encode_box_autoadd_fuzzy_config(config, serializer);
        sse_encode_opt_box_autoadd_u_32(limit, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_fuzzy_hit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusFilterConstMeta,
      argValues: [that, query, config, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusFilterConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_filter",
        argNames: ["that", "query", "config", "limit"],
      );

  @override
  Future<List<FuzzyHit>> crateApiFuzzyFuzzyCorpusFilterAsync(
      {required FuzzyCorpus that,
      required String query,
      required FuzzyConfig config,
      int? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        sse_encode_String(query, serializer);
        sse_encode_box_autoadd_fuzzy_config(config, serializer);
        sse_encode_opt_box_autoadd_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_fuzzy_hit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusFilterAsyncConstMeta,
      argValues: [that, query, config, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusFilterAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_filter_async",
        argNames: ["that", "query", "config", "limit"],
      );

  @override
  void crateApiFuzzyFuzzyCorpusFree({required FuzzyCorpus that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusFreeConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusFreeConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_free",
        argNames: ["that"],
      );

  @override
  bool crateApiFuzzyFuzzyCorpusIsEmpty({required FuzzyCorpus that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusIsEmptyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusIsEmptyConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_is_empty",
        argNames: ["that"],
      );

  @override
  bool crateApiFuzzyFuzzyCorpusIsHydrated({required FuzzyCorpus that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusIsHydratedConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusIsHydratedConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_is_hydrated",
        argNames: ["that"],
      );

  @override
  int crateApiFuzzyFuzzyCorpusLen({required FuzzyCorpus that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusLenConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusLenConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_len",
        argNames: ["that"],
      );

  @override
  FuzzyCorpus crateApiFuzzyFuzzyCorpusNew(
      {required List<String> items, required bool ignoreCaseIndices}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(items, serializer);
        sse_encode_bool(ignoreCaseIndices, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusNewConstMeta,
      argValues: [items, ignoreCaseIndices],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusNewConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_new",
        argNames: ["items", "ignoreCaseIndices"],
      );

  @override
  void crateApiFuzzyFuzzyCorpusRehydrate({required FuzzyCorpus that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusRehydrateConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusRehydrateConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_rehydrate",
        argNames: ["that"],
      );

  @override
  void crateApiFuzzyFuzzyCorpusRemoveIndices(
      {required FuzzyCorpus that, required List<int> indices}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        sse_encode_list_prim_u_32_loose(indices, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusRemoveIndicesConstMeta,
      argValues: [that, indices],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusRemoveIndicesConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_remove_indices",
        argNames: ["that", "indices"],
      );

  @override
  void crateApiFuzzyFuzzyCorpusSetAt(
      {required FuzzyCorpus that, required int index, required String item}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
            that, serializer);
        sse_encode_u_32(index, serializer);
        sse_encode_String(item, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusSetAtConstMeta,
      argValues: [that, index, item],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusSetAtConstMeta =>
      const TaskConstMeta(
        debugName: "FuzzyCorpus_set_at",
        argNames: ["that", "index", "item"],
      );

  @override
  FuzzyConfig crateApiFuzzyDefaultFuzzyConfig() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_fuzzy_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyDefaultFuzzyConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyDefaultFuzzyConfigConstMeta =>
      const TaskConstMeta(
        debugName: "default_fuzzy_config",
        argNames: [],
      );

  @override
  Future<FuzzyConfig> crateApiFuzzyFuzzyConfigDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_fuzzy_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyConfigDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "fuzzy_config_default",
        argNames: [],
      );

  @override
  Future<FuzzyCorpus> crateApiFuzzyFuzzyCorpusNewAsync(
      {required List<String> items, required bool ignoreCaseIndices}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(items, serializer);
        sse_encode_bool(ignoreCaseIndices, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyCorpusNewAsyncConstMeta,
      argValues: [items, ignoreCaseIndices],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyCorpusNewAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "fuzzy_corpus_new_async",
        argNames: ["items", "ignoreCaseIndices"],
      );

  @override
  List<FuzzyHit> crateApiFuzzyFuzzyFilter(
      {required String query,
      required List<String> items,
      required FuzzyConfig config,
      int? limit}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_list_String(items, serializer);
        sse_encode_box_autoadd_fuzzy_config(config, serializer);
        sse_encode_opt_box_autoadd_u_32(limit, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_fuzzy_hit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyFilterConstMeta,
      argValues: [query, items, config, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyFilterConstMeta => const TaskConstMeta(
        debugName: "fuzzy_filter",
        argNames: ["query", "items", "config", "limit"],
      );

  @override
  Future<List<FuzzyHit>> crateApiFuzzyFuzzyFilterAsync(
      {required String query,
      required List<String> items,
      required FuzzyConfig config,
      int? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_list_String(items, serializer);
        sse_encode_box_autoadd_fuzzy_config(config, serializer);
        sse_encode_opt_box_autoadd_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_fuzzy_hit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyFilterAsyncConstMeta,
      argValues: [query, items, config, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyFilterAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "fuzzy_filter_async",
        argNames: ["query", "items", "config", "limit"],
      );

  @override
  int? crateApiFuzzyFuzzyMatch(
      {required String query,
      required String haystack,
      required FuzzyConfig config}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_String(haystack, serializer);
        sse_encode_box_autoadd_fuzzy_config(config, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyMatchConstMeta,
      argValues: [query, haystack, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyMatchConstMeta => const TaskConstMeta(
        debugName: "fuzzy_match",
        argNames: ["query", "haystack", "config"],
      );

  @override
  FuzzyMatch? crateApiFuzzyFuzzyMatchIndices(
      {required String query,
      required String haystack,
      required FuzzyConfig config}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_String(haystack, serializer);
        sse_encode_box_autoadd_fuzzy_config(config, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_fuzzy_match,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiFuzzyFuzzyMatchIndicesConstMeta,
      argValues: [query, haystack, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFuzzyFuzzyMatchIndicesConstMeta =>
      const TaskConstMeta(
        debugName: "fuzzy_match_indices",
        argNames: ["query", "haystack", "config"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_FuzzyCorpus => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_FuzzyCorpus => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus;

  @protected
  FuzzyCorpus
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FuzzyCorpusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FuzzyCorpus
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FuzzyCorpusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FuzzyCorpus
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FuzzyCorpusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  FuzzyCorpus
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FuzzyCorpusImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FuzzyConfig dco_decode_box_autoadd_fuzzy_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fuzzy_config(raw);
  }

  @protected
  FuzzyMatch dco_decode_box_autoadd_fuzzy_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_fuzzy_match(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  FuzzyConfig dco_decode_fuzzy_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FuzzyConfig(
      ignoreCase: dco_decode_bool(arr[0]),
      normalize: dco_decode_bool(arr[1]),
      preferPrefix: dco_decode_bool(arr[2]),
      mode: dco_decode_match_mode(arr[3]),
      parallel: dco_decode_bool(arr[4]),
      incremental: dco_decode_bool(arr[5]),
    );
  }

  @protected
  FuzzyHit dco_decode_fuzzy_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FuzzyHit(
      index: dco_decode_u_32(arr[0]),
      score: dco_decode_u_32(arr[1]),
      indices: dco_decode_list_prim_u_32_strict(arr[2]),
    );
  }

  @protected
  FuzzyMatch dco_decode_fuzzy_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FuzzyMatch(
      score: dco_decode_u_32(arr[0]),
      indices: dco_decode_list_prim_u_32_strict(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FuzzyHit> dco_decode_list_fuzzy_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_fuzzy_hit).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MatchMode dco_decode_match_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MatchMode.values[raw as int];
  }

  @protected
  FuzzyMatch? dco_decode_opt_box_autoadd_fuzzy_match(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_fuzzy_match(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  FuzzyCorpus
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FuzzyCorpusImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FuzzyCorpus
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FuzzyCorpusImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FuzzyCorpus
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FuzzyCorpusImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  FuzzyCorpus
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return FuzzyCorpusImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FuzzyConfig sse_decode_box_autoadd_fuzzy_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fuzzy_config(deserializer));
  }

  @protected
  FuzzyMatch sse_decode_box_autoadd_fuzzy_match(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_fuzzy_match(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  FuzzyConfig sse_decode_fuzzy_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ignoreCase = sse_decode_bool(deserializer);
    var var_normalize = sse_decode_bool(deserializer);
    var var_preferPrefix = sse_decode_bool(deserializer);
    var var_mode = sse_decode_match_mode(deserializer);
    var var_parallel = sse_decode_bool(deserializer);
    var var_incremental = sse_decode_bool(deserializer);
    return FuzzyConfig(
        ignoreCase: var_ignoreCase,
        normalize: var_normalize,
        preferPrefix: var_preferPrefix,
        mode: var_mode,
        parallel: var_parallel,
        incremental: var_incremental);
  }

  @protected
  FuzzyHit sse_decode_fuzzy_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_score = sse_decode_u_32(deserializer);
    var var_indices = sse_decode_list_prim_u_32_strict(deserializer);
    return FuzzyHit(index: var_index, score: var_score, indices: var_indices);
  }

  @protected
  FuzzyMatch sse_decode_fuzzy_match(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_score = sse_decode_u_32(deserializer);
    var var_indices = sse_decode_list_prim_u_32_strict(deserializer);
    return FuzzyMatch(score: var_score, indices: var_indices);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FuzzyHit> sse_decode_list_fuzzy_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FuzzyHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_fuzzy_hit(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MatchMode sse_decode_match_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MatchMode.values[inner];
  }

  @protected
  FuzzyMatch? sse_decode_opt_box_autoadd_fuzzy_match(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_fuzzy_match(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          FuzzyCorpus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FuzzyCorpusImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          FuzzyCorpus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FuzzyCorpusImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          FuzzyCorpus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FuzzyCorpusImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFuzzyCorpus(
          FuzzyCorpus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as FuzzyCorpusImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_fuzzy_config(
      FuzzyConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fuzzy_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_fuzzy_match(
      FuzzyMatch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_fuzzy_match(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_fuzzy_config(FuzzyConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ignoreCase, serializer);
    sse_encode_bool(self.normalize, serializer);
    sse_encode_bool(self.preferPrefix, serializer);
    sse_encode_match_mode(self.mode, serializer);
    sse_encode_bool(self.parallel, serializer);
    sse_encode_bool(self.incremental, serializer);
  }

  @protected
  void sse_encode_fuzzy_hit(FuzzyHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_u_32(self.score, serializer);
    sse_encode_list_prim_u_32_strict(self.indices, serializer);
  }

  @protected
  void sse_encode_fuzzy_match(FuzzyMatch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.score, serializer);
    sse_encode_list_prim_u_32_strict(self.indices, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_fuzzy_hit(
      List<FuzzyHit> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_fuzzy_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint32List(self is Uint32List ? self : Uint32List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_match_mode(MatchMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_fuzzy_match(
      FuzzyMatch? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_fuzzy_match(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class FuzzyCorpusImpl extends RustOpaque implements FuzzyCorpus {
  // Not to be used by end users
  FuzzyCorpusImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  FuzzyCorpusImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_FuzzyCorpus,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_FuzzyCorpus,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_FuzzyCorpusPtr,
  );

  /// 末尾追加（不重建）。同步维护 Utf32 索引与折叠副本。
  void add({required List<String> items}) => RustLib.instance.api
      .crateApiFuzzyFuzzyCorpusAdd(that: this, items: items);

  /// 清空全部候选（保留实例与驻留状态）。
  void clear() => RustLib.instance.api.crateApiFuzzyFuzzyCorpusClear(
        that: this,
      );

  /// 过滤已缓存的语料。`Fuzzy` 按分数降序；其余按原序。
  List<FuzzyHit> filter(
          {required String query, required FuzzyConfig config, int? limit}) =>
      RustLib.instance.api.crateApiFuzzyFuzzyCorpusFilter(
          that: this, query: query, config: config, limit: limit);

  /// `filter` 的异步版本：frb worker 线程执行，不阻塞 UI。
  Future<List<FuzzyHit>> filterAsync(
          {required String query, required FuzzyConfig config, int? limit}) =>
      RustLib.instance.api.crateApiFuzzyFuzzyCorpusFilterAsync(
          that: this, query: query, config: config, limit: limit);

  /// 释放占内存大头的 Utf32 索引（与折叠副本），保留源字符串便于 `rehydrate`。幂等。
  void free() => RustLib.instance.api.crateApiFuzzyFuzzyCorpusFree(
        that: this,
      );

  bool isEmpty() => RustLib.instance.api.crateApiFuzzyFuzzyCorpusIsEmpty(
        that: this,
      );

  bool isHydrated() => RustLib.instance.api.crateApiFuzzyFuzzyCorpusIsHydrated(
        that: this,
      );

  int len() => RustLib.instance.api.crateApiFuzzyFuzzyCorpusLen(
        that: this,
      );

  /// 从源字符串重建 Utf32 索引（及折叠副本，若启用）。无跨 FFI 编组开销。幂等。
  void rehydrate() => RustLib.instance.api.crateApiFuzzyFuzzyCorpusRehydrate(
        that: this,
      );

  /// 批量按下标删除（内部降序去重）。
  void removeIndices({required List<int> indices}) => RustLib.instance.api
      .crateApiFuzzyFuzzyCorpusRemoveIndices(that: this, indices: indices);

  /// 替换指定下标（越界忽略）。
  void setAt({required int index, required String item}) => RustLib.instance.api
      .crateApiFuzzyFuzzyCorpusSetAt(that: this, index: index, item: item);
}
