// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_haystacks`, `case_matching`, `make_matcher`, `make_pattern`, `normalization`, `rank_and_truncate`

/// 便捷构造默认配置，供 Dart 侧直接调用。
FuzzyConfig defaultFuzzyConfig() =>
    RustLib.instance.api.crateApiFuzzyDefaultFuzzyConfig();

/// 对单个字符串打分；不匹配返回 `None`（Dart 侧为 `int?`）。
int? fuzzyMatch({
  required String query,
  required String haystack,
  required FuzzyConfig config,
}) => RustLib.instance.api.crateApiFuzzyFuzzyMatch(
  query: query,
  haystack: haystack,
  config: config,
);

/// 对单个字符串打分并返回命中字符下标；不匹配返回 `None`。
FuzzyMatch? fuzzyMatchIndices({
  required String query,
  required String haystack,
  required FuzzyConfig config,
}) => RustLib.instance.api.crateApiFuzzyFuzzyMatchIndices(
  query: query,
  haystack: haystack,
  config: config,
);

/// 对列表做模糊筛选，按分数降序（同分保持原顺序）返回命中项；
/// `limit` 为可选的结果数量上限（Dart 侧为 `int?`）。
List<FuzzyHit> fuzzyFilter({
  required String query,
  required List<String> items,
  required FuzzyConfig config,
  int? limit,
}) => RustLib.instance.api.crateApiFuzzyFuzzyFilter(
  query: query,
  items: items,
  config: config,
  limit: limit,
);

/// 异步版本：不标记 `#[frb(sync)]`，frb 会在独立 worker 线程上执行，**不阻塞 Dart UI 线程**。
/// 适合超大数据集或不希望卡顿的场景（Dart 侧返回 `Future<List<FuzzyHit>>`）。
/// 比 Dart 的 `compute` 更省：无需把数据拷进新 isolate，直接在 Rust 线程算。
Future<List<FuzzyHit>> fuzzyFilterAsync({
  required String query,
  required List<String> items,
  required FuzzyConfig config,
  int? limit,
}) => RustLib.instance.api.crateApiFuzzyFuzzyFilterAsync(
  query: query,
  items: items,
  config: config,
  limit: limit,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FuzzyCorpus>>
abstract class FuzzyCorpus implements RustOpaqueInterface {
  /// 增量追加候选项到末尾(不重建索引)。已驻留则同步追加 Utf32 索引;
  /// 未驻留(已 free)只追加源,下次 rehydrate 一并生效。O(追加量)。
  void add({required List<String> items});

  /// 清空全部候选(保留实例与驻留状态)。
  void clear();

  /// 仅传入查询串即可过滤已缓存的语料，按分数降序（同分保持原序）返回命中项。
  /// 若已 `free`，则从源字符串临时转换匹配（仍无需跨 FFI 重传列表）。
  List<FuzzyHit> filter({
    required String query,
    required FuzzyConfig config,
    int? limit,
  });

  /// `filter` 的异步版本：在 frb worker 线程执行，不阻塞 UI（Dart 侧返回 `Future`）。
  /// 语料仍常驻 Rust 侧，调用只跨 FFI 传查询串。
  Future<List<FuzzyHit>> filterAsync({
    required String query,
    required FuzzyConfig config,
    int? limit,
  });

  /// 释放占内存大头的 Utf32 索引，但**保留实例与源字符串**，便于低成本 `rehydrate`。
  /// free 后内存回落到约「源字符串」大小（ASCII 下约为驻留态的 1/5）。
  /// 幂等。free 状态下 `filter` 仍可用（每次从源临时转换，较慢，但无需跨 FFI 重传列表）。
  void free();

  /// 是否为空。
  bool isEmpty();

  /// 是否已驻留 Utf32 索引（free 后为 false）。
  bool isHydrated();

  /// 当前语料条目数。
  int len();

  /// 用一组候选项构建语料（一次性，类似建索引）。
  factory FuzzyCorpus({required List<String> items}) =>
      RustLib.instance.api.crateApiFuzzyFuzzyCorpusNew(items: items);

  /// 从驻留的源字符串重建 Utf32 索引，恢复快速搜索。**无跨 FFI 编组开销**（源已在 Rust 侧）。
  /// 已驻留时为空操作。
  void rehydrate();

  /// 批量按下标删除(内部降序去重删除,避免位移错乱)。
  void removeIndices({required List<int> indices});

  /// 替换指定下标的候选(越界忽略)。O(1)。
  void setAt({required int index, required String item});
}

/// 模糊匹配配置。
class FuzzyConfig {
  /// 忽略大小写。true => `CaseMatching::Ignore`，false => `CaseMatching::Respect`。
  final bool ignoreCase;

  /// Unicode 归一化（影响带变音符号字符的匹配）。true => `Normalization::Smart`，false => `Never`。
  final bool normalize;

  /// 是否给「以查询开头」的结果额外加分，使前缀匹配排名更靠前。
  final bool preferPrefix;

  const FuzzyConfig({
    required this.ignoreCase,
    required this.normalize,
    required this.preferPrefix,
  });

  static Future<FuzzyConfig> default_() =>
      RustLib.instance.api.crateApiFuzzyFuzzyConfigDefault();

  @override
  int get hashCode =>
      ignoreCase.hashCode ^ normalize.hashCode ^ preferPrefix.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FuzzyConfig &&
          runtimeType == other.runtimeType &&
          ignoreCase == other.ignoreCase &&
          normalize == other.normalize &&
          preferPrefix == other.preferPrefix;
}

/// 列表筛选命中项：`index` 指回原列表，`score` 为匹配分，`indices` 为命中字符下标。
class FuzzyHit {
  final int index;
  final int score;
  final Uint32List indices;

  const FuzzyHit({
    required this.index,
    required this.score,
    required this.indices,
  });

  @override
  int get hashCode => index.hashCode ^ score.hashCode ^ indices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FuzzyHit &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          score == other.score &&
          indices == other.indices;
}

/// 单次匹配结果：分数 + 命中的字符下标（升序去重，用于 UI 高亮）。
class FuzzyMatch {
  final int score;
  final Uint32List indices;

  const FuzzyMatch({required this.score, required this.indices});

  @override
  int get hashCode => score.hashCode ^ indices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FuzzyMatch &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          indices == other.indices;
}
