// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_folded`, `build_haystacks`, `build`, `case_matching`, `clear_caches`, `filter_nonfuzzy`, `finish_fuzzy`, `fold_pair`, `fuzzy_filter_hydrated`, `fuzzy_rank_items`, `incr_cap`, `indices_one`, `lazy_folded`, `make_matcher`, `make_pattern`, `nonfuzzy_filter`, `nonfuzzy_match_indices`, `normalization`, `num_threads`, `rank_scored`, `scan_haystacks_parallel`, `scan_haystacks_serial`, `scan_haystacks`, `scan_one`, `scan_subset`, `should_parallel`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IncrCache`, `Scored`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// 便捷构造默认配置，供 Dart 侧直接调用。
FuzzyConfig defaultFuzzyConfig() =>
    RustLib.instance.api.crateApiFuzzyDefaultFuzzyConfig();

/// 对单个字符串打分；不匹配返回 `None`。简单/子序列模式命中返回 `Some(0)`。
int? fuzzyMatch(
        {required String query,
        required String haystack,
        required FuzzyConfig config}) =>
    RustLib.instance.api.crateApiFuzzyFuzzyMatch(
        query: query, haystack: haystack, config: config);

/// 对单个字符串打分并返回命中字符下标；不匹配返回 `None`。
FuzzyMatch? fuzzyMatchIndices(
        {required String query,
        required String haystack,
        required FuzzyConfig config}) =>
    RustLib.instance.api.crateApiFuzzyFuzzyMatchIndices(
        query: query, haystack: haystack, config: config);

/// 对列表做筛选。`Fuzzy` 按分数降序，其余按原序（命中满 `limit` 即停）。
List<FuzzyHit> fuzzyFilter(
        {required String query,
        required List<String> items,
        required FuzzyConfig config,
        int? limit}) =>
    RustLib.instance.api.crateApiFuzzyFuzzyFilter(
        query: query, items: items, config: config, limit: limit);

/// 异步版本：在 frb worker 线程执行，不阻塞 Dart UI 线程。
Future<List<FuzzyHit>> fuzzyFilterAsync(
        {required String query,
        required List<String> items,
        required FuzzyConfig config,
        int? limit}) =>
    RustLib.instance.api.crateApiFuzzyFuzzyFilterAsync(
        query: query, items: items, config: config, limit: limit);

/// 异步构建语料：在 frb worker 线程执行 Utf32 转换/折叠（大数据时较重），**不阻塞 Dart UI 线程**。
/// 与 [FuzzyCorpus::new] 等价，只是不标 `#[frb(sync)]`（Dart 侧返回 `Future<FuzzyCorpus>`）。
/// 注：候选列表的跨 FFI 编组同样在 worker 线程；但 Dart 侧的投影（stringOf）仍在调用线程算。
Future<FuzzyCorpus> fuzzyCorpusNewAsync({required List<String> items}) =>
    RustLib.instance.api.crateApiFuzzyFuzzyCorpusNewAsync(items: items);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FuzzyCorpus>>
abstract class FuzzyCorpus implements RustOpaqueInterface {
  /// 末尾追加（不重建）。同步维护 Utf32 索引。
  void add({required List<String> items});

  /// 清空全部候选（保留实例与驻留状态）。
  void clear();

  /// 过滤已缓存的语料。`Fuzzy` 按分数降序；其余按原序。
  List<FuzzyHit> filter(
      {required String query, required FuzzyConfig config, int? limit});

  /// `filter` 的异步版本：frb worker 线程执行，不阻塞 UI。
  Future<List<FuzzyHit>> filterAsync(
      {required String query, required FuzzyConfig config, int? limit});

  /// 释放占内存大头的 Utf32 索引，保留源字符串便于 `rehydrate`。幂等。
  void free();

  bool isEmpty();

  bool isHydrated();

  int len();

  /// 用一组候选项构建语料。
  factory FuzzyCorpus({required List<String> items}) =>
      RustLib.instance.api.crateApiFuzzyFuzzyCorpusNew(items: items);

  /// 从源字符串重建 Utf32 索引。无跨 FFI 编组开销。幂等。
  void rehydrate();

  /// 批量按下标删除（内部降序去重）。
  void removeIndices({required List<int> indices});

  /// 替换指定下标（越界忽略）。
  void setAt({required int index, required String item});
}

/// 模糊匹配配置。`ignore_case` 按查询传，其余仅 `Fuzzy` 相关。
class FuzzyConfig {
  /// 忽略大小写。
  final bool ignoreCase;

  /// Unicode 归一化（仅 `Fuzzy` 生效；简单模式忽略）。
  final bool normalize;

  /// 前缀优先（仅 `Fuzzy` 的排序生效）。
  final bool preferPrefix;

  /// 匹配模式。
  final MatchMode mode;

  /// 是否允许多核并行（仅 `Fuzzy` 搜索；按候选数阈值自动决定，小数据/简单模式/web 仍单线程）。
  /// 建索引的 Utf32 转换始终按数据量自动并行（一次性、纯提速，不受此开关影响）。
  final bool parallel;

  /// 是否启用增量搜索缓存（仅 `FuzzyCorpus` + `Fuzzy` 模式生效）：当本次查询是上次查询的
  /// **追加扩展**（前缀，同 ignore_case/normalize）时，只在上次命中集内重扫（命中单调收缩）。
  /// 任何增删改/free 都会清缓存。默认 false。
  final bool incremental;

  const FuzzyConfig({
    required this.ignoreCase,
    required this.normalize,
    required this.preferPrefix,
    required this.mode,
    required this.parallel,
    required this.incremental,
  });

  static Future<FuzzyConfig> default_() =>
      RustLib.instance.api.crateApiFuzzyFuzzyConfigDefault();

  @override
  int get hashCode =>
      ignoreCase.hashCode ^
      normalize.hashCode ^
      preferPrefix.hashCode ^
      mode.hashCode ^
      parallel.hashCode ^
      incremental.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FuzzyConfig &&
          runtimeType == other.runtimeType &&
          ignoreCase == other.ignoreCase &&
          normalize == other.normalize &&
          preferPrefix == other.preferPrefix &&
          mode == other.mode &&
          parallel == other.parallel &&
          incremental == other.incremental;
}

/// 列表筛选命中项：`index` 指回原列表，`score` 为匹配分，`indices` 为命中字符下标。
class FuzzyHit {
  final int index;
  final int score;
  final Uint32List indices;

  const FuzzyHit({
    required this.index,
    required this.score,
    required this.indices,
  });

  @override
  int get hashCode => index.hashCode ^ score.hashCode ^ indices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FuzzyHit &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          score == other.score &&
          indices == other.indices;
}

/// 单次匹配结果：分数 + 命中的字符下标（升序去重，用于 UI 高亮）。
class FuzzyMatch {
  final int score;
  final Uint32List indices;

  const FuzzyMatch({
    required this.score,
    required this.indices,
  });

  @override
  int get hashCode => score.hashCode ^ indices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FuzzyMatch &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          indices == other.indices;
}

/// 匹配模式。
enum MatchMode {
  /// nucleo 子序列模糊匹配 + 打分 + 排序（默认）。
  fuzzy,

  /// 精确子串：`haystack` 包含 `query`。
  substring,

  /// 前缀：`haystack` 以 `query` 开头。
  prefix,

  /// 全词：`haystack` 与 `query` 完全相等。
  word,
  ;
}
